//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmadeusApiIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeatAvailabilityDetail
    {
        public int travelerId { get; set; }
        public Nullable<int> segmentId { get; set; }
        public Nullable<int> flightOfferId { get; set; }
        public string cabin { get; set; }
        public string Seat_Number { get;  set; }
        public string Seat_total_Price { get; set; }
        public string Seat_base_Price { get; set; }
        public string Taxes_Amount { get; set; }
        public string coordinates { get; set; }
        public string seatAvailabilityStatus { get; set; }
    
        public virtual flightDetail flightDetail { get; set; }
    }
}
