//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmadeusApiIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeatMap_deckConfiguration
    {
        public int travelerId { get; set; }
        public Nullable<int> segmentId { get; set; }
        public Nullable<int> flightOfferId { get; set; }
        public string deckType { get; set; }
        public Nullable<int> width { get; set; }
        public Nullable<int> length { get; set; }
        public Nullable<int> startSeatRow { get; set; }
        public Nullable<int> endSeatRow { get; set; }
        public Nullable<int> startWingsX { get; set; }
        public Nullable<int> endWingsX { get; set; }
        public Nullable<int> startWingsRow { get; set; }
        public Nullable<int> endWingsRow { get; set; }
        public string exitRowsX { get; set; }
    
        public virtual flightDetail flightDetail { get; set; }
    }
}
